### ISSUE TITLE
Would love to have some minimal documentation about how sub groups work

### ISSUE THREAD

**Issue by nimrod-cohen** [AkaySoftware/CodeIgniter-Aauth#156]
I mean,
do they inherit permissions? can they override permissions?
if a user is part of a sub group, will he be identified as a member of the parent group? and vice versa?
If I add a user to a parent group, than add him to one of the sub groups, than remove him from the parent group, will he be removed from the sub group as well?

thanks in advance, and thanks for writing this great piece of code!

**Comment by REJack** [comment]
sub groups aka `group_to_group` doesn't work with users, it needs still some enhancements i started it with #115 :smiley: 


>  do they inherit permissions? can they override permissions?

not really, its more a merge of perms

>  if a user is part of a sub group, will he be identified as a member of the parent group? and vice versa?

over `is_member` not, but it should :dizzy_face: 
at the moment you can only check the perms of a subgroup trough the parent group with `is_group_allowed()`

>  If I add a user to a parent group, than add him to one of the sub groups, than remove him from the parent group, will he be removed from the sub group as well?

You mean add user to subgroup with `add_member()` (but this wouldn't needed if you have used `add_subgroup` but then it would the sub group as well)? If yes it wont be removed from the sub group.

**Comment by tswagger** [comment]
If the Parent/Child Group Permissions is not fully implemented, this does bring up a good point.  Should the permissions trickle up or trickle down.  In other words: Should the child inherit all of the parents permissions, or should the parent gain all of the child’s permissions?


On Jun 27, 2016, at 5:01 PM, Raphael Jackstadt <notifications@github.com> wrote:

sub groups aka group_to_group doesn't work with users, it needs still some enhancements i started it with #115 <https://github.com/emreakay/CodeIgniter-Aauth/issues/115> 😃

do they inherit permissions? can they override permissions?

not really, its more a merge of perms

if a user is part of a sub group, will he be identified as a member of the parent group? and vice versa?

over is_member not, but it should 😵 
at the moment you can only check the perms of a subgroup trough the parent group with is_group_allowed()

If I add a user to a parent group, than add him to one of the sub groups, than remove him from the parent group, will he be removed from the sub group as well?

You mean add user to subgroup with add_member() (but this wouldn't needed if you have used add_subgroup but then it would the sub group as well)? If yes it wont be removed from the sub group.

**Comment by REJack** [comment]
At the moment the parent group gains all of the child groups permissions.

A little example :smile: 

If you have 3 groups with perms
 - Main Group
    - has Perms: MainPerm1
 - Grp1
    - has Perms: Sub1Perm1, Sub1Perm2
 - Grp2
    - has Perms: Sub2Perm1

and you add `Grp1` & `Grp2` as subgroup to `Main Group`, then the `Main Group` gains all perms of the subgroup.
 - Main Group
     - Perms: MainPerm1, Sub1Perm1 & Sub1Perm2(trough Grp1), Sub2Perm1 (trough Grp2)


I'm personally think a child should not gain all parent perms.

**Comment by nimrod-cohen** [comment]
I guess its a matter of philosophy, I would personally naturally assume that the whole idea is similar to class inheritance, parent has certain capabilities, and a child extend them with more specific extra capabilities.
but as I said, philosophy.

**Comment by REJack** [comment]
correct its like [Multiple inheritance](https://en.wikipedia.org/wiki/Multiple_inheritance)

**Comment by REJack** [comment]
issue done? :smile: If yes please close the issue.

**Comment by REJack** [comment]
I think this issue is done, I'll close it now 😃.
