### ISSUE TITLE
AJAX support ?

### ISSUE THREAD

**Issue by tpw1314** [AkaySoftware/CodeIgniter-Aauth#161]
Hi, this isn't really an issue but I would like to know if you guys will include support for AJAX live updating as well ?

Ion Auth was having issue with AJAX regarding session problem. So I am just wondering if Aauth will be / is the one that supports flexibility with AJAX ?

**Comment by nimrod-cohen** [comment]
I'm doing everything with AJAX, no problems here.

**Comment by paulcanning** [comment]
I don't see why it wouldn't work with AJAX? It's just a different method of sending and receiving data.

**Comment by kikuyu1** [comment]
It working well with AJAX

**Comment by firhanyulianto** [comment]
no problem with ajax, but....

**Comment by paulcanning** [comment]
@firhanyulianto but what?

**Comment by perenstrom** [comment]
The suspense!

**Comment by firhanyulianto** [comment]
@paulcanning nope hahaha

**Comment by paulcanning** [comment]
@firhanyulianto what the heck are you on about?

**Comment by REJack** [comment]
I think this issue is done too, I'll close it now 😃.
